global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grpcserver'
    static_configs:
      - targets: ['grpcserver:9090']
  - job_name: 'grpcgateway'
    static_configs:
      - targets: ['grpcgateway:9090']